/// Flutter Web implementation of [BibleService] database opening.
///
/// This file is selected at compile time by the conditional import in
/// `bible_service.dart` when `dart.library.io` is NOT available — i.e., on
/// Flutter Web. It must **never** be imported directly; always go through the
/// conditional import in `bible_service.dart`.
///
/// ## How web SQLite works here
///
/// The browser has no writable native file system, so sqflite's standard
/// file-based open cannot be used directly. Instead, this implementation:
///
///   1. Redirects the global sqflite `databaseFactory` to
///      `databaseFactoryFfiWebNoWebWorker`, which routes all database
///      operations through a WebAssembly sqlite3 build backed by
///      **IndexedDB** in the browser.
///
///   2. On the **first page load**, loads the bundled `eng-web.db` asset
///      bytes from the Flutter bundle and writes them into IndexedDB via
///      `databaseFactory.writeDatabaseBytes`. This takes 1-3 seconds
///      (28.9 MB write) but only happens once.
///
///   3. On **subsequent page loads**, detects that the database already
///      exists in IndexedDB and skips the write step entirely, making cold
///      start much faster (just WASM loading + IndexedDB open, ~0.5s).
///
///   4. Opens the database read-only and returns a standard sqflite
///      [Database] handle. From this point on, [BibleService] queries it
///      exactly like the native file-based implementation.
///
/// ## Persistence
///
/// Unlike a pure in-memory approach, data written to IndexedDB **persists
/// across page reloads**. The bundled WEB Bible is effectively "installed"
/// on first load. Phase 3.2 will extend this pattern to support multiple
/// downloaded Bibles with proper version-checking and storage management.
///
/// ## Required web/ files
///
/// `sqflite_common_ffi_web` loads `web/sqlite3.wasm` automatically when the
/// factory initialises. This file is generated by:
///
///   dart run sqflite_common_ffi_web:setup
///
/// `web/sqflite_sw.js` (also generated by the setup tool) is **not** used by
/// the no-worker factory variant, but can be left in place without harm.
library;

import 'dart:typed_data' show Uint8List;

import 'package:flutter/services.dart' show rootBundle;
import 'package:path/path.dart' as p;
import 'package:sqflite/sqflite.dart' show Database, openReadOnlyDatabase;
import 'package:sqflite_common/sqflite.dart' show databaseFactory;
import 'package:sqflite_common_ffi_web/sqflite_ffi_web.dart'
    show databaseFactoryFfiWebNoWebWorker;

// No hardcoded filename constant here — the stored name is derived from
// assetPath at call time via p.basename(), so that this function works
// correctly for any Bible translation asset without clobbering another.

/// Opens the Bible database on Flutter Web.
///
/// [assetPath] is the Flutter asset path of the bundled `.db` file,
/// e.g. 'assets/bibles/eng-web.db'. On the first call the bytes are
/// loaded from the app bundle and written into browser IndexedDB. On
/// subsequent calls (across page reloads) the write is skipped because
/// the database file already exists in IndexedDB.
///
/// The IndexedDB key is derived from the basename of [assetPath]
/// (e.g. 'eng-web.db'), so different Bible assets are stored under
/// distinct keys and cannot overwrite each other.
///
/// Returns an open sqflite [Database] handle ready for read-only queries.
/// The caller ([BibleService.ensureOpen]) caches this for the lifetime of
/// the page session.
Future<Database> platformOpenDatabase(String assetPath) async {
  // -- Step 1: Redirect the global sqflite factory to the web implementation --
  //
  // databaseFactoryFfiWebNoWebWorker routes all sqflite database operations
  // through a WebAssembly sqlite3 build backed by browser IndexedDB. The
  // "no web worker" variant runs entirely on the main thread, keeping setup
  // simple and avoiding the shared-worker infrastructure.
  //
  // This factory is lazy -- it only loads sqlite3.wasm and opens the IndexedDB
  // store on the first method call, so no expensive work happens here.
  databaseFactory = databaseFactoryFfiWebNoWebWorker;

  // -- Step 2: Resolve the full virtual path for the database ----------------
  //
  // On web, getDatabasesPath() returns '/'. Joining the basename of assetPath
  // gives e.g. '/eng-web.db'. Deriving the name from assetPath ensures
  // different Bible translations are stored under distinct IndexedDB keys.
  final dbsPath = await databaseFactory.getDatabasesPath();
  final dbFileName = p.basename(assetPath); // e.g. 'eng-web.db'
  final fullPath = p.join(dbsPath, dbFileName);

  // -- Step 3: Seed IndexedDB with asset bytes on the very first page load ---
  //
  // If the database file already exists in IndexedDB we skip the write, making
  // subsequent cold starts fast (no need to reload the 28.9 MB asset).
  // On the very first load the write takes 1-3 seconds.
  //
  // KNOWN LIMITATION (Phase 1): if a future app release ships an updated
  // eng-web.db, the databaseExists() guard will prevent the new bytes from
  // being written — existing web users will silently keep the stale copy.
  // Phase 3.2 (Bible library download infrastructure) will replace this with
  // a versioned strategy: compare a bundled version marker against the stored
  // one and re-seed when the app-bundled DB is newer.
  if (!await databaseFactory.databaseExists(fullPath)) {
    // Load the bundled .db file from the Flutter asset bundle as raw bytes.
    final byteData = await rootBundle.load(assetPath);
    final Uint8List bytes = byteData.buffer.asUint8List(
      byteData.offsetInBytes,
      byteData.lengthInBytes,
    );

    // Write the bytes into IndexedDB through the sqflite ffi web layer.
    // The factory handles the IndexedDB transaction and flush internally.
    await databaseFactory.writeDatabaseBytes(fullPath, bytes);
  }

  // -- Step 4: Open the database read-only and return the handle -------------
  //
  // The database now exists in IndexedDB. openReadOnlyDatabase routes through
  // the global databaseFactory (set above), which opens the file from IndexedDB
  // via the WebAssembly sqlite3 layer. singleInstance: true ensures sqflite
  // returns the same handle if this is somehow called more than once.
  return openReadOnlyDatabase(fullPath, singleInstance: true);
}
